# Generated by Django 3.2.6 on 2021-10-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Sell'), (3, 'Blocked')], default=1),
        ),
        migrations.AlterField(
            model_name='reporttype',
            name='type',
            field=models.IntegerField(choices=[(1, 'Spam'), (2, 'Cheat')], default=1),
        ),
    ]
