# Generated by Django 3.2.6 on 2021-12-18 07:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20211112_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
