# Generated by Django 3.2.6 on 2021-12-12 08:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20211112_2154'),
        ('order', '0002_alter_cart_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200, null=True)),
                ('total', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('delivery_day', models.DateField()),
                ('status', models.IntegerField(choices=[(1, 'Delivered'), (2, 'Waiting'), (3, 'Accepted'), (4, 'Cancel')], default=2)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='post.post')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payee_email', models.EmailField(max_length=254)),
                ('payment_id', models.CharField(max_length=100)),
                ('payer_id', models.CharField(max_length=100)),
                ('authentication', models.IntegerField(choices=[(1, 'Active'), (2, 'Inactive')], default=2)),
                ('checkout', models.BooleanField(default=False)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
        migrations.DeleteModel(
            name='OrderDetail',
        ),
    ]
