# Generated by Django 3.2.6 on 2021-12-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20211212_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_day',
            field=models.DateField(null=True),
        ),
    ]
