# Generated by Django 3.2.6 on 2021-12-12 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_rename_total_order_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
    ]
