# Generated by Django 3.2.6 on 2021-12-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_order_payee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payee_email',
            field=models.EmailField(max_length=254),
        ),
    ]
