# Generated by Django 3.2.6 on 2021-12-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20211217_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='district',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='street',
            field=models.CharField(max_length=100),
        ),
    ]
