# Generated by Django 3.2.6 on 2021-12-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20211217_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='buyer',
        ),
        migrations.AddField(
            model_name='payment',
            name='buyer',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
