# Generated by Django 3.2.6 on 2021-12-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_auto_20211218_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='buyer',
            field=models.CharField(max_length=200),
        ),
    ]
